FPS = 60

BOARDWIDTH = 4
BOARDHEIGHT = 4

WINDOWWIDTH = 800
WINDOWHEIGHT = 600
FIELDSIZE = 80

XMARGIN = int((WINDOWWIDTH - (FIELDSIZE * (BOARDWIDTH))) // 2)
YMARGIN = int((WINDOWHEIGHT - (FIELDSIZE * (BOARDHEIGHT))) // 2)

BGCOLOR = (20, 20, 150)
FIELDCOLOR = (20, 150, 20)
FONTCOLOR = (0, 0, 0)
FIELDFRAME = (0, 0, 0)
BOARDFRAME = (128, 0, 0)

FONTSIZE = 20

VOIDFIELD = WINDOWHEIGHT * WINDOWWIDTH